name: Send genshin-db_release repository dispatch

on:
  release:
    types: [published]

jobs:
  genshin-db_release:
    strategy:
      matrix:
        repo: ['theBowja/genshin-db-dist']
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PUBLIC_REPO_PAT }}
          repository: ${{ matrix.repo }}
          event-type: genshin-db_release
          client-payload: '{"tagname": "${{ github.ref_name}}"}'